"""Add login tracking fields

Revision ID: 0a16e2098bb7
Revises: fb22dd580e25
Create Date: 2026-06-11 23:55:40.047588
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a16e2098bb7'
down_revision: Union[str, None] = 'fb22dd580e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'last_login_date')
    # ### end Alembic commands ###
