"""Add learning materials models

Revision ID: 84e743168b53
Revises: 
Create Date: 2026-06-07 14:10:00.766378
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84e743168b53'
down_revision: Union[str, None] = '000000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.create_foreign_key('fk_teacher_quizzes_document_id', 'teacher_quizzes', 'faculty_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_teacher_quizzes_teacher_id', 'teacher_quizzes', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'teacher_quizzes', type_='foreignkey')
    op.drop_constraint(None, 'teacher_quizzes', type_='foreignkey')
    # ### end Alembic commands ###
