"""Add learning materials models

Revision ID: 84e743168b53
Revises: 
Create Date: 2026-06-07 14:10:00.766378
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '84e743168b53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'teacher_quizzes', 'faculty_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'teacher_quizzes', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('student', 'faculty', 'admin', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'student'"))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('student', 'faculty', 'admin', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'student'"))
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'teacher_quizzes', type_='foreignkey')
    op.drop_constraint(None, 'teacher_quizzes', type_='foreignkey')
    # ### end Alembic commands ###
