"""Add attempt_type

Revision ID: f4844c81ea1e
Revises: 0a16e2098bb7
Create Date: 2026-06-14 19:19:46.821293
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f4844c81ea1e'
down_revision: Union[str, None] = '0a16e2098bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_analytics_id'), table_name='topic_analytics')
    op.drop_table('topic_analytics')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_faculty_reports_id'), table_name='faculty_reports')
    op.drop_table('faculty_reports')
    op.drop_index(op.f('ix_material_interactions_id'), table_name='material_interactions')
    op.drop_table('material_interactions')
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'topic')
    op.drop_column('documents', 'source_type')
    op.drop_column('documents', 'ocr_text')
    op.drop_column('documents', 'transcript')
    op.drop_column('documents', 'chunks_count')
    op.drop_column('documents', 'summary')
    op.drop_constraint(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'teacher_quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.alter_column('quizzes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('quizzes_creator_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_document_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'quiz_source')
    op.drop_column('quizzes', 'num_questions')
    op.drop_column('quizzes', 'document_id')
    op.drop_column('quizzes', 'question_type')
    op.drop_column('quizzes', 'creator_id')
    op.drop_column('quizzes', 'difficulty')
    op.drop_constraint(op.f('student_answers_question_id_fkey'), 'student_answers', type_='foreignkey')
    op.create_foreign_key(None, 'student_answers', 'teacher_quiz_questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_answers', type_='foreignkey')
    op.create_foreign_key(op.f('student_answers_question_id_fkey'), 'student_answers', 'quiz_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.add_column('quizzes', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('num_questions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('quiz_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('quizzes_document_id_fkey'), 'quizzes', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('quizzes_creator_id_fkey'), 'quizzes', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.alter_column('quizzes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('chunks_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('ocr_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('doc_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_table('material_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.id'], name=op.f('material_interactions_material_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('material_interactions_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('material_interactions_pkey'))
    )
    op.create_index(op.f('ix_material_interactions_id'), 'material_interactions', ['id'], unique=False)
    op.create_table('faculty_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('report_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ai_recommendations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('faculty_reports_quiz_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('faculty_reports_teacher_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('faculty_reports_pkey'))
    )
    op.create_index(op.f('ix_faculty_reports_id'), 'faculty_reports', ['id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('violation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_snippet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('system_logs_performed_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user'], ['users.id'], name=op.f('system_logs_target_user_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('system_logs_pkey'))
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subtopic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bloom_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_questions_quiz_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_questions_pkey'))
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_table('topic_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtopic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], name=op.f('topic_analytics_attempt_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('topic_analytics_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_analytics_pkey'))
    )
    op.create_index(op.f('ix_topic_analytics_id'), 'topic_analytics', ['id'], unique=False)
    # ### end Alembic commands ###
